### ISSUE TITLE
ender cabinet crash when using moving drawer

### ISSUE THREAD

**Issue by ehwuts** [bafomdad/realfilingcabinet#2] opened 2016-08-05 03:44 UTC
crash log: http://pastebin.com/raw/qxUnynnU
steps to reproduce:
place cabinet
put something (like dirt in folder
put folder in cabinet
apply ender upgrade to cabinet
rclick and shift+rclick a few times

**Comment by bafomdad** [comment] 2016-08-05 09:38
cannot reproduce with build. 

reasoning:
- the .jar file released elsewhere is older
- the mod version in this repo has not been incremented to tell people it is newer

solution:
- commit a change to increment mod version by 1

**Comment by ehwuts** [comment] 2016-08-08 19:07
could not reproduce with fresh pack and redownload of latest release

**Comment by bafomdad** [comment] 2016-08-09 17:37
aight, let's close it until it comes up again

**Closed by bafomdad** 2016-08-09 17:37 UTC
